Task/student
vladyslav-yermolin-moc/react-mentors-test-2024 pull request #2
Opened 2024-03-15 13:55 UTC by electrovladyslav

2024-04-04 15:29 UTC, gulchizxvr requested changes

2024-04-04 15:29 UTC, gulchizxvr commented on src/ProductPage.module.css
> +.product__image {
Привести назви класів до одного виду (kebab case)

2024-04-04 15:29 UTC, gulchizxvr commented on src/ProductPage.tsx
> +interface Product {
Винести окремо всі інтерфейси

2024-04-04 15:29 UTC, gulchizxvr commented on src/ProductPage.tsx
> +  const fetchProducts = async () => {
Функції для отримання даних сервера винести з основного компоненту

2024-04-04 15:29 UTC, gulchizxvr commented on src/ProductPage.tsx
> +  const filterProducts = () => {
Функцію винести в окрему папку на рівні з компонентом. Наприклад, винести всі функції в папку helpers

2024-04-04 15:29 UTC, gulchizxvr commented on src/ProductPage.tsx
> +  const sortProducts = () => {
Функцію винести в окрему папку на рівні з компонентом.

2024-04-04 15:29 UTC, gulchizxvr commented on src/ProductPage.tsx
> +          <div key={product.id} className={css.product}>
Винести окремо компоненту Product

2024-04-04 15:29 UTC, gulchizxvr commented on src/App.tsx
>      <>
Зайвий тег

2024-04-04 15:29 UTC, gulchizxvr commented on src/ProductPage.module.css
> +.productList {
Привести назви класів до одного виду (kebab case)

2024-04-04 15:29 UTC, gulchizxvr commented on src/ProductPage.tsx
> +    console.log(data);
прибрати console.log

2024-04-05 08:23 UTC, closed without merging

2024-04-05 08:23 UTC, vladyslav-yermolin-moc commented
Hey @gulchizxvr, thanks for your review.
[Here](https://github.com/vladyslav-yermolin-moc/react-mentors-test-2024/wiki/%5BFlow%5D-%D0%AF%D0%BA-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D1%96%D1%80%D1%8F%D1%82%D0%B8-%D0%B4%D0%BE%D0%BC%D0%B0%D1%88%D0%BA%D0%B8-%D0%B2%D1%96%D0%B4-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D1%96%D0%B2) I described the our recommendation, to check the real pull requests from the students